### ISSUE TITLE
Remove trusted_mod requirement

### ISSUE THREAD

**Issue by rubenwardy** [minetest-mods/wiki#5]
There's no good reason for this mod to require the insecure environment. If this is needed to read from other mod's dirs then it should be made so other mods provide pages themselves.

**Comment by valerio-bozzolan** [comment]
At the moment the application tries to access `minetest.request_insecure_environment().io.open()` to open files.

Is there another way to open files?

**Comment by rubenwardy** [comment]
You can just use io.open to read files

**Comment by valerio-bozzolan** [comment]
Is this OK now?
